// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lszpjkwevnfvxtmlqaxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzenBqa3dldm5mdnh0bWxxYXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTkxNjYsImV4cCI6MjA2NjkzNTE2Nn0.xq788DDv8qsKfD9IXAdU-o18x4qPjiTQ0P1WepTrxYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});